In [2]:
import pandas as pd
import numpy as np

### Assessment 0

In [45]:
def fizz_buzz():
    '''Returns the numbers from 1 to 100 into list. But for
    multiples of three append "Fizz" instead of the number and for the multiples
    of five append "Buzz". For numbers which are multiples of both three and five
    append "FizzBuzz".

    The first five elements of the output list are:
        lst = [1, 2, "Fizz", 4, "Buzz", ....]

    Parameters
    ----------
    None

    Returns
    -------
    list
    
    fizzlst = []
    for num in range(1,101):
        if num%3==0 and num%5==0: fizzlst.append('Fizzbuzz')
        elif num%3==0: fizzlst.append('Fizz')
        elif num%5==0: fizzlst.append('Buzz')
        else: fizzlst.append(num)
        
    return fizzlst
    '''
    fizzlst = ["FizzBuzz" if num%3==0 and num%5==0 else "Fizz" if num%3==0 else "Buzz" if num%5==0 else num for num in range(1,101)]
    return fizzlst


In [46]:
def count_characters(string):
    '''
    Return a dictionary which contains
    a count of the number of times each character appears in the string.
    Characters which with a count of 0 should not be included in the
    output dictionary.

    FOR FULL POINTS DON'T USE IMPORTS.

    Parameters
    ----------
    string: str

    Returns
    -------
    dict
        A dictionary with counts of each character in string
    
    d = {}
    for let in string:
        if let not in d:
            d[let] = 1
        else:
            d[let] += 1
    '''
    d = {letter:string.count(letter) for letter in string}
    return d


In [50]:
def merge_dictionaries(d1, d2):
    '''Returns a new dictionary containing all the keys from d1 and d2 with
    their associated values. If a key is in both dictionaries, the new value is
    the sum of the two values from d1 and d2.

    FOR FULL POINTS DON'T USE IMPORTS AND MAXIMUM ONE LOOP.

    Parameters
    ----------
    d1, d2: dictionary, dictionary

    Returns
    -------
    dictionary
    
    d = d1.copy()
    for key, value in d2.items():
        d[key] = d.get(key, 0) + value
    return d
    
    STUDY THIS: return {k: d1.get(k, 0) + d2.get(k, 0) for k in (set(d1) | set(d2))}
    '''
    d = d1.copy()
    for k, v in d2.items():
        if k in d:
            d[k] += v
        else:
            d[k] = v
    return d


In [43]:
def cookie_jar(a, b):
    '''
    There are two jars of cookies.
    Each has chocolate and peanut butter cookies.
    Input 'a' is the fraction of cookies in Jar A which are chocolate.
    Input 'b' is the fraction of cookies in Jar B which are chocolate.
    A jar is chosen at random and a cookie is drawn.
    The cookie is chocolate.
    Return the probability that the cookie came from Jar A.

    Parameters
    ----------
    a: float
        Probability of drawing a chocolate cooking from Jar A
    b: float
        Probability of drawing a chocolate cooking from Jar B

    Returns
    -------
    float
        Conditional probability that cookie was drawn from Jar A given
        that a chocolate cookie was drawn.    
    '''
    return a / a+b

In [52]:
def boolean_indexing(arr, minimum):
    '''Return an array of only the elements of "arr" that are greater than
    or equal to "minimum".

    FOR FULL POINTS DON'T USE LOOPS OR LIST COMPREHENSIONS.

    Parameters
    ----------
    arr: NumPy array  
    minimum: int

    Returns
    -------
    NumPy array
        Of elements of arr that are >= minimum

    >>>boolean_indexing(np.array([[3, 4, 5], [6, 7, 8]]), 7)
    array([7, 8])
    '''
    return arr[arr >= minimum]


array([7, 8])

In [55]:
def size_of_multiply(A, B):
    '''If matrices A (dimensions m x n) and B (dimensions p x q) can be
    multiplied (AB), returns the shape of the result of multiplying them.
    Function DOES NOT perform the multiplication. If A and B cannot be
    multiplied, returns None. (Use the shape function.)

    DO NOT PERFORM ANY MATRIX MULTIPLICATION IN YOUR FUNCTION.

    Parameters
    ----------
    A, B: NumPy array, NumPy array

    Returns
    -------
    (int, int) or None  
    '''
    if A.shape[1] == B.shape[0]: return (A.shape[0], B.shape[1]) 
    else: return None
    

In [58]:
def data_frame_work(df, colA, colB, colC):
    '''
    Insert a column (colC) into the dataframe that is the sum of
    colA and colB. Assume that df contains columns colA and colB and
    that these are numeric.

    Parameters
    ----------
    df: Pandas DataFrame
    colA, colB, colC: str, str, str
    '''
    
    df[colC] = colA + colB


### Assessment 1

In [61]:
def max_lists(list1, list2):
    '''Compares the elements of list1, and list2 (assumed to be the same
    length),and returns the maximum value between the two, for each element.

    FOR FULL POINTS DON'T USE IMPORTS.

    Parameters
    ----------
    list1, list2: list, list
        (Of the same length)

    Returns
    -------
    list
    '''
    maxes = []
    for val1, val2 in zip(list1, list2):
        if val1 > val2: 
            maxes.append(val1)
        else: 
            maxes.append(val2)
    return maxes

In [ ]:
def invert_dictionary(d):
    '''
    Given a dictionary d, return a new dictionary with d's values
    as keys and the value for a given key being
    the set of d's keys which shared the same value.

    Parameters
    ----------
    d: dict

    Returns
    -------
    dict
        A dictionary of sets of input keys indexing the same input values
        indexed by the input values.


    >>>invert_dictionary({'a': 2, 'b': 4, 'c': 2})
    {2: {'a', 'c'}, 4: {'b'}}
    '''
    pass

In [ ]:
def matrix_multiplication(A, B):
    '''Return the matrix which is the product of matrix A and matrix B
    where A and B will be (a) integer valued (b) square matrices
    (c) of size n-by-n (d) encoded as lists of lists,  e.g.
    A = [[2, 3, 4], [6, 4, 2], [-1, 2, 0]] corresponds to the matrix
    | 2  3  4 |
    | 6  4  2 |
    |-1  2  0 |

    YOU MAY NOT USE NUMPY. Write your solution in straight python.

    Parameters
    ----------
    a, b: list of lists of integers, list of lists integers
        All inner/outer lists are of length n, so as to construct square
        matrices.

    Returns
    -------
    list of lists of integers
        The product of a matrix multiplication operation.
    '''
    pass

In [ ]:
def reverse_index(arr, finRow, finCol):
    '''
    Reverse the row order of "arr" (i.e. so the top row is on the bottom)
    and return the sub-matrix from coordinate [0, 0] up to
    (but not including) [finRow, finCol].

    Hint: this can use two steps of slicing, which can be combined into
    a one-liner.

    FOR FULL POINTS DON'T USE LOOPS OR LIST COMPREHENSIONS.

    Parameters
    ----------
    arr: NumPy array
    finRow, finCol: int, int


    Returns
    -------
    NumPy array    
      Of an "upside down" subset of arr

    >>>arr = np.array([[ -4,  -3,  11],
                       [ 14,   2, -11],
                       [-17,  10,   3]])
    >>>reverse_index(arr, 2, 2)
    array([[-17, 10],
           [ 14,  2]])
    '''
    pass

In [ ]:
import numpy as np

def array_work(rows, cols, scalar, matrixA):
    '''
    Create matrix of size (rows, cols) with elements initialized to the
    scalar value. Right multiply that matrix with the passed matrixA
    (i.e. AB, not BA).  Return the result of the multiplication.  You
    needn't check for matrix compatibility, but you can accomplish this in
    a single line.

    Parameters
    ----------
    rows, cols: int, int
        Size of matrix to be created
    scalar: int
        Value of each element of new matrix
    matrixA:

    Returns
    -------
    NumPy array
        Result of matrix product of row-by-col matrix of "scalar"'s times
        matrixA.

    E.g., array_work(2, 3, 5, [[3, 4], [5, 6], [7, 8]])
           [[3, 4],      [[5, 5, 5],
            [5, 6],   *   [5, 5, 5]]
            [7, 8]]
    '''
    pass

In [1]:
df = pandas.read_csv('https://s3-us-west-2.amazonaws.com/learn-assets.galvanize.com/gSchool/ds-curriculum/sql-block/rent.csv')

NameError: name 'pandas' is not defined

In [ ]:
def pandas_add_increase_column(df):
    '''Adds a column to the DataFrame called 'Increase' which contains the
    amount that the median rent increased by from 2011 to 2014.

    Parameters
    ----------
    df: Pandas DataFrame

    Returns
    -------
    None
    '''
    pass

In [ ]:
def pandas_max_rent(df):
    '''Returns a new pandas DataFrame that contains every city and the highest
    median rent from that city for 2011 and 2014.

    Note that city names are not unique so the state is tracked as well.
    For example, Portland, ME and Portland, OR are recognized as different.

    Parameters
    ----------
    df: Pandas DataFrame

    Returns
    -------
    Pandas DataFrame:
        Containing the columns: City, State, med_2011, med_2014
    '''
    cpy = df.copy()

### Assessment 2

In [ ]:
def roll_the_dice(n_simulations = 1000):
    '''Two unbiased, six sided, dice are thrown one time and the sum of the
    faces is observed (so if you rolled a 3 and a 1, the sum is 4). A
    simulation estimates probability that the total score is an even number
    or a number greater than 7.  This is an estimated probability, based on
    rolling the two dice n_simulations times.

    FOR FULL POINTS, THE FUNCTION MUST PERFORM A SIMULATION.

    Parameters
    ----------
    n_simulations: float
        Number of rolls of the dice

    Returns
    -------
    float
    '''
    pass

In [ ]:
import numpy as np
assessment_scores = np.array([
    [20,40],
    [40,60],
    [35,50],
    [50,50],
    [22, 26],
    [44, 38],
    [44, 52]
])

def return_percentage_greater_than_80(arr):
  '''
  Return the percentage of the rows in arr where the sum of the two values is greater than 80. 
  *You should use numpy to do this.* 

  Parameters
  ==========
  arr: 2 dimensional numpy array

  Returns
  ======
  percentage: float
  '''
  return arr

In [ ]:
def only_positive(arr):
    '''Return a numpy array containing only the rows from arr where all
    the values in that row are positive.

    FOR FULL POINTS USE NUMPY METHODS AND NO LOOPS OR LIST COMPREHENSIONS.

    Parameters
    ----------
    arr: Numpy Array (2-dimensional)

    Returns
    -------
    NumPy Array (2-dimensional)

    Example
    =======
    arr = np.array([
        [1, -1, 2],
        [3, 4, 2],
        [-8, 4, -4]
        ])
    
    only_positive(arr) returns:
    np.array([[3, 4, 2]])
    '''
    pass

In [ ]:
import pandas
df = pandas.read_csv("https://s3-us-west-2.amazonaws.com/learn-assets.galvanize.com/gSchool/ds-curriculum/sql-block/universities.csv")

def pandas_query(df):
    '''Returns a DataFrame containing the average size of each university
    type ordered by average size in ascending order.

    Function assumes the input DataFrame contains these columns:
        name, address, Website, Type, Size

    Parameters
    ----------
    df: Pandas DataFrame

    Returns
    -------
    Pandas DataFrame
    '''
    pass

In [ ]:
import pandas as pd

def return_loans_by_id(df):
    '''
    Takes a df and returns a df with only the requested loans.

    Parameters
    ==========
    df: Pandas DataFrame

    Returns
    =======
    Pandas DataFrame
    '''
    pass

In [ ]:
import pandas as pd

def return_loans(df):
    '''
    Takes a df and returns a df with only the requested loans.

    Parameters
    ==========
    df: Pandas DataFrame

    Returns
    =======
    Pandas DataFrame
    '''
    pass