In [1]:
import numpy as np
import pandas as pd

https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [2]:
print(np.__version__)

1.19.2


In [3]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr1 = np.full((3,3), True, dtype=bool)
arr1 = np.full((3,3), True, dtype=bool)
arr1 = np.ones((3,3), dtype=bool)
arr1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0]

array([1, 3, 5, 7, 9])

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_copy = arr.copy()
arr_copy[arr_copy % 2 != 0] = -1
print(arr_copy, arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1] [0 1 2 3 4 5 6 7 8 9]


In [8]:
arr = np.arange(10)
out = np.where(arr %2 != 0, -1, arr)
print(arr, out)

[0 1 2 3 4 5 6 7 8 9] [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [9]:
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a, b), axis = 0)
np.vstack((a,b))
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.concatenate((a,b), axis=1)
np.hstack((a,b))
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [12]:
a = np.array([1,2,3])
np.concatenate((np.repeat(a, 3), np.concatenate((a,a,a))))
np.concatenate((np.repeat(a, 3), np.tile(a,3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [13]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.array([i for i in a if i not in b])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [14]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [15]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

a[np.where(np.logical_and(a >= 5, a <= 10))]
a[np.where((a>=5)&(a<=10))]
a[(a>=5)&(a<=10)]

array([ 6,  9, 10])

In [16]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

def maxx2(x, y):
    """Get the maximum of two items"""
                   
    return np.max(np.vstack((x, y)), axis=0)

In [17]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

maxx2(a, b)

pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

In [18]:
arr = np.arange(9).reshape(3,3)
arr[:,[0,1]] = arr[:,[1,0]]
arr[:,[1,0,2]]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
arr = np.arange(9).reshape(3,3)
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [20]:
arr = np.arange(9).reshape(3,3)
arr[[2,1,0],:]
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [21]:
arr = np.arange(9).reshape(3,3)
arr[:,[2,1,0]]
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [22]:
arr = np.random.uniform(low=5, high=10, size=15).reshape(5,3)
arr = np.random.uniform(low=5, high=10, size=(5,3))
arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
arr

array([[6.71698565, 7.12077322, 7.63505253],
       [9.56524079, 6.11735746, 8.41897875],
       [5.62057013, 5.15826898, 6.53732664],
       [9.10248795, 6.67969852, 8.36190282],
       [5.17890429, 5.59446665, 9.85766694]])

In [23]:
rand_arr = np.random.random((5,3))
np.round(rand_arr, 3)
np.set_printoptions(precision=3)
rand_arr

array([[0.392, 0.763, 0.543],
       [0.844, 0.7  , 0.151],
       [0.295, 0.12 , 0.386],
       [0.213, 0.157, 0.461],
       [0.832, 0.569, 0.077]])

In [24]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(precision=6, suppress=True)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [25]:
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [26]:
np.set_printoptions(threshold=np.inf)
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [27]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None, encoding=None)
iris_col5 = np.array([row[4] for row in iris_1d])
iris_col5[:5]

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], dtype='<U15')

In [28]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None, encoding=None, usecols=(0,1,2,3))
iris_2d = np.array([list(row) for row in iris_1d])
iris_ = np.array([row.tolist()[:4] for row in iris_1d])

In [29]:
from scipy.stats import stats
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepal = np.genfromtxt(url, delimiter=',', dtype='float', usecols=0)

print(f'mean: {np.mean(sepal)}')
print(f'median: {np.median(sepal)}')
print(f'std: {np.std(sepal)}')

stats.describe(sepal)

mean: 5.843333333333334
median: 5.8
std: 0.8253012917851409


DescribeResult(nobs=150, minmax=(4.3, 7.9), mean=5.843333333333334, variance=0.6856935123042507, skewness=0.3117530585022963, kurtosis=-0.5735679489249765)

In [30]:
#29
from sklearn import preprocessing

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepal = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepals = sepal.reshape(1, -1)
preprocessing.normalize(sepals)

norm = lambda x: (x-np.min(sepal)) / (np.max(sepal)-np.min(sepal))
sep_lst = [round(norm(x), 3) for x in sepal]
print(sep_lst)

sep_normed = np.round(np.apply_along_axis(func1d=norm, axis=0, arr=sepal), 3)
print(sep_normed)

smax, smin = sepal.max(), sepal.min()
s1 = np.round((sepal-smin)/(smax-smin), 3)
print(s1)

s2 = np.round((sepal-smin)/sepal.ptp(), 3)
print(s2)

[0.222, 0.167, 0.111, 0.083, 0.194, 0.306, 0.083, 0.194, 0.028, 0.167, 0.306, 0.139, 0.139, 0.0, 0.417, 0.389, 0.306, 0.222, 0.389, 0.222, 0.306, 0.222, 0.083, 0.222, 0.139, 0.194, 0.194, 0.25, 0.25, 0.111, 0.139, 0.306, 0.25, 0.333, 0.167, 0.194, 0.333, 0.167, 0.028, 0.222, 0.194, 0.056, 0.028, 0.194, 0.222, 0.139, 0.222, 0.083, 0.278, 0.194, 0.75, 0.583, 0.722, 0.333, 0.611, 0.389, 0.556, 0.167, 0.639, 0.25, 0.194, 0.444, 0.472, 0.5, 0.361, 0.667, 0.361, 0.417, 0.528, 0.361, 0.444, 0.5, 0.556, 0.5, 0.583, 0.639, 0.694, 0.667, 0.472, 0.389, 0.333, 0.333, 0.417, 0.472, 0.306, 0.472, 0.667, 0.556, 0.361, 0.333, 0.333, 0.5, 0.417, 0.194, 0.361, 0.389, 0.389, 0.528, 0.222, 0.389, 0.556, 0.417, 0.778, 0.556, 0.611, 0.917, 0.167, 0.833, 0.667, 0.806, 0.611, 0.583, 0.694, 0.389, 0.417, 0.583, 0.611, 0.944, 0.944, 0.472, 0.722, 0.361, 0.944, 0.556, 0.667, 0.806, 0.528, 0.5, 0.583, 0.806, 0.861, 1.0, 0.583, 0.556, 0.5, 0.944, 0.556, 0.583, 0.472, 0.722, 0.667, 0.722, 0.417, 0.694, 0.667, 0.667

In [31]:
#30
from scipy.special import softmax

def my_softmax(vector):
    e = np.exp(vector)
    return e / e.sum()

result_1 = my_softmax(sepals)
print(result_1.sum())

result_2 = softmax(sepals)
print(result_2.sum())

0.9999999999999999
1.0000000000000007


In [32]:
#31
np.percentile(sepals, [5, 95])

array([4.6  , 7.255])

In [33]:
#32
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
index_nan = np.random.choice(iris_2d.size, 20, replace=False)
iris_2d.ravel()[index_nan] = np.nan

# # Method 1
# i, j = np.where(iris_2d)
# np.random.seed(100)
# iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan

# # Method 2
# np.random.seed(100)
# iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [34]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
# print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))
print(np.sum(np.isnan(iris_2d)[:, 0]))
print(np.where(np.isnan(iris_2d)[:, 0]))

4
(array([13, 26, 38, 97]),)


In [35]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


In [36]:
iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [37]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [38]:
iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [39]:
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [40]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

cor = np.corrcoef(iris_2d[:, 0], iris_2d[:, 2])[0, 1]

from scipy.stats.stats import pearsonr
corr, p_value = pearsonr(iris_2d[:, 0], iris_2d[:, 2])
print(corr, p_value)
print(cor)

0.8717541573048713 1.0384540627941062e-47
0.8717541573048718


In [41]:
#37
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.isnan(iris_2d).any()

False

In [42]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

mask = np.isnan(iris_2d)
iris_2d[mask] = 0
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 0. , 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [0. , 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 0. , 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 0. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 0. , 1.5, 0.1],
       [0. , 4.2, 1.4, 0.2],
       [0. , 3

In [43]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

print(np.unique(iris))

species = np.array([row.tolist()[4] for row in iris])

np.unique(species, return_counts=True)

[b'0.1' b'0.2' b'0.3' b'0.4' b'0.5' b'0.6' b'1.0' b'1.1' b'1.2' b'1.3'
 b'1.4' b'1.5' b'1.6' b'1.7' b'1.8' b'1.9' b'2.0' b'2.1' b'2.2' b'2.3'
 b'2.4' b'2.5' b'2.6' b'2.7' b'2.8' b'2.9' b'3.0' b'3.1' b'3.2' b'3.3'
 b'3.4' b'3.5' b'3.6' b'3.7' b'3.8' b'3.9' b'4.0' b'4.1' b'4.2' b'4.3'
 b'4.4' b'4.5' b'4.6' b'4.7' b'4.8' b'4.9' b'5.0' b'5.1' b'5.2' b'5.3'
 b'5.4' b'5.5' b'5.6' b'5.7' b'5.8' b'5.9' b'6.0' b'6.1' b'6.2' b'6.3'
 b'6.4' b'6.5' b'6.6' b'6.7' b'6.8' b'6.9' b'7.0' b'7.1' b'7.2' b'7.3'
 b'7.4' b'7.6' b'7.7' b'7.9' b'Iris-setosa' b'Iris-versicolor'
 b'Iris-virginica']


(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'),
 array([50, 50, 50]))

In [44]:
#40
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# iris[iris[:, 3] < 3] = 'small'
type(iris[:,2][0])
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

In [45]:
from math import pi

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

petal_length = iris_2d[:, 2].astype('float') 
sepal_length = iris_2d[:, 0].astype('float')

volume = (pi * petal_length * sepal_length**2) / 3

# volume = volume[:, np.newaxis] OR
volume = np.reshape(volume, (-1, 1))

final = np.hstack([iris_2d, volume])

final[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004]], dtype=object)

In [46]:
#42
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

species = iris[:, 4]

np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out1 = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])

probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, 0.750, num=50), np.linspace(0.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150))
species_out2 = species[index]

In [47]:
# print(len(species_out1))
# print(len(probs))
# print(len(index))
# print(len(species_out2))

In [48]:
#43
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

petal_len_setosa = iris[iris[:, 4] == b'Iris-setosa', [2]].astype('float')

np.unique(np.sort(petal_len_setosa))[-2]

1.7

In [50]:
#44
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

iris[iris[:, 0].argsort()]

array([[b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'3.0', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.5', b'2.3', b'1.3', b'0.3', b'Iris-setosa'],
       [b'4.6', b'3.6', b'1.0', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'4.6', b'3.2', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.3', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.9', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.1', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.9', b'2.4', b'3.3', b'1.0', b'Iris-versicolor'],
       [b'4.9', b'2.5', b'4

In [55]:
#45
col = iris[:, 2]

vals, counts = np.unique(col, return_counts=True)

vals[np.argmax(counts)]

b'1.5'

In [79]:
#46
np.argwhere(iris[:, 3].astype(float) >= 1.0)[0]

array([50])

In [89]:
#47
np.random.seed(100)
a = np.random.uniform(1,50, 20)
# a[a > 30] = 30
# a[a < 10] = 10
# OR
# np.clip(a, a_min=10, a_max=30)
# OR
np.where(a<10, 10, np.where(a>30, 30, a))

array([27.626842, 14.6401  , 21.801362, 30.      , 10.      , 10.      ,
       30.      , 30.      , 10.      , 29.179573, 30.      , 11.250904,
       10.081083, 10.      , 11.765177, 30.      , 30.      , 10.      ,
       30.      , 14.429614])

In [37]:
#48
np.random.seed(100)
a = np.random.uniform(1,50, 20)

print("Solution 1:", a.argsort()[::-1][:5])
print("Solution 2:", np.argpartition(-a, 5)[:5])
# These methods will provide values
a[a.argsort()][-5:]
np.sort(a)[-5:]
np.partition(a, kth=-5)[-5:]
a[np.argpartition(-a, 5)][:5]

Solution 1: [15 10  3  7 18]
Solution 2: [15 10  3  7 18]


array([48.95256545, 44.67477576, 42.39403048, 41.466785  , 40.99501269])

In [50]:
#49
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))

def row_wise_val_count(array):
    
    num_counts_array = [np.unique(row, return_counts=True) for row in array]
    
    return num_counts_array

arr_ = [9,  9,  4,  8,  8,  1,  5,  3,  6,  3]

arr

np.unique(arr_, return_counts=True)

print(row_wise_val_count(arr))

[(array([1, 3, 4, 5, 6, 8, 9]), array([1, 2, 1, 1, 1, 2, 2])), (array([ 1,  2,  3,  5,  7,  9, 10]), array([2, 1, 3, 1, 1, 1, 1])), (array([2, 4, 5, 6, 8]), array([3, 2, 3, 1, 1])), (array([ 1,  3,  4,  6,  8,  9, 10]), array([1, 2, 1, 1, 2, 1, 2])), (array([1, 2, 3, 6, 7, 8, 9]), array([2, 2, 2, 1, 1, 1, 1])), (array([ 1,  2,  3,  4,  5,  6,  9, 10]), array([1, 1, 1, 1, 1, 2, 2, 1]))]
