In [1]:
import numpy as np
import pandas as pd

https://www.machinelearningplus.com/python/101-pandas-exercises-python/

In [2]:
print(pd.__version__)

1.1.3


In [3]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

series_mylist = pd.Series(mylist)
series_myarr = pd.Series(myarr)
series_mydict = pd.Series(mydict)

In [4]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

df = pd.DataFrame(ser).reset_index()
df = ser.to_frame().reset_index()

In [5]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

df = pd.concat([ser1, ser2], axis=1)
df = pd.DataFrame({'col1':ser1, 'col2':ser2})

In [6]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'), name='alphabets')
ser.name = 'alphabets'

In [7]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser1[~ser1.isin(ser2)]
pd.Series(np.setdiff1d(ser1, ser2))

0    1
1    2
2    3
dtype: int64

In [8]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

union = pd.Series(np.union1d(ser1, ser2))
intersect = pd.Series(np.intersect1d(ser1, ser2))
notcommon = union[~union.isin(intersect)]

In [9]:
state = np.random.RandomState(100)
ser = pd.Series(np.random.normal(10, 5, 25))
ser.describe()
np.percentile(ser,q=[0,25,50,75,100])

array([ 0.79313596,  7.69168411,  9.96102804, 13.34623102, 18.6567793 ])

In [10]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.value_counts()

g    8
f    6
e    6
b    4
a    2
d    2
c    1
h    1
dtype: int64

In [11]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
ser_sorted = ser.sort_values(ascending=False)
top_val = ser.value_counts().index[:2]
ser[~ser.isin(top_val)] = 'Other'
ser

0         3
1     Other
2         2
3         2
4         2
5         2
6     Other
7         2
8     Other
9         3
10        3
11        3
dtype: object

In [12]:
ser = pd.Series(np.random.random(20))
labelz = ['1st','2nd','3rd','4th','5th','6th','7th','8th','9th','10th']
qz = np.linspace(0, 1, 11)
pd.qcut(ser,
       q=qz,
       labels=labelz)

0      6th
1      3rd
2      1st
3      4th
4      5th
5      4th
6      9th
7      6th
8      8th
9     10th
10     1st
11     3rd
12    10th
13     7th
14     8th
15     7th
16     2nd
17     2nd
18     9th
19     5th
dtype: category
Categories (10, object): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']

In [13]:
ser = pd.Series(np.random.randint(1, 10, 35))
ser_arr = np.array(ser).reshape(7,5)
ser_df = pd.DataFrame(ser_arr)

ser_df = pd.DataFrame(ser.values.reshape(7,5))
ser_df

0  1  2  3  4
0  6  8  7  9  1
1  4  9  6  1  5
2  2  7  9  9  2
3  7  2  1  9  8
4  4  2  2  2  8
5  4  1  5  8  1
6  5  4  1  2  4

In [14]:
ser = pd.Series(np.random.randint(1, 10, 7))
out = np.argwhere(ser.values % 3 == 0)
out

array([[5]])

In [15]:
# 14
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

ser.loc[pos]
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [16]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

vert = pd.DataFrame(ser1.append(ser2))
horz = pd.concat([ser1, ser2], axis=1)

In [17]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

[pd.Index(ser1).get_loc(i) for i in ser2]
[np.where(i==ser1)[0].tolist()[0] for i in ser2]

[5, 4, 0, 8]

In [18]:
#17

In [19]:
[np.where(i==ser1)[0].tolist()[0] for i in ser2]

[5, 4, 0, 8]

In [20]:
i = []
for idx, num in enumerate(ser1.tolist()):
    if num in ser2.tolist():
        i.append(idx)
i

[0, 4, 5, 8]

In [21]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

ser.map(lambda x: x.capitalize())
ser.map(lambda x: x[0].upper() + x[1:])
pd.Series([i.capitalize() for i in ser])

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [22]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
ser.map(lambda x: len(x))
pd.Series([len(x) for x in ser])

0    3
1    2
2    4
3    4
dtype: int64

In [23]:
#20
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


In [24]:
import datetime
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
ser_dt = pd.to_datetime(ser)
print(ser_dt)

from dateutil.parser import parse
ser.map(lambda x: parse(x))


0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]


0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [25]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
ser_dt = pd.to_datetime(ser)
print('Date: ', ser_dt.dt.day.tolist())
print('Week number: ', ser_dt.dt.weekofyear.tolist())
print('Day number of year: ', ser_dt.dt.dayofyear.tolist())
print('Day of week: ', ser_dt.dt.weekday.tolist())

Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day number of year:  [1, 33, 63, 94, 125, 157]
Day of week:  [4, 2, 5, 3, 0, 5]


/home/bobbyhuck/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  after removing the cwd from sys.path.


In [26]:
#23
from dateutil.parser import parse

ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
ser_result = ser.map(lambda d: parse('4' + d))
ser_result

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [27]:
#24
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

def extract(word):
    vowels = 'aeiou'
    count = 0
    for letter in word.lower():
        if letter in vowels:
            count +=1
    if count >= 2:
        return True
    else:
        return False
        
result_mask = ser.apply(lambda x: extract(x) == True)
ser[result_mask]

0     Apple
1    Orange
4     Money
dtype: object

In [28]:
#25
import re

# The regex variable has the following symbols:
#     ^: Anchor for the start of the string
#     [ ]: Opening and closing square brackets define a character class to match a single character
#     \ : Escape character
#     . : The dot matches any character except the newline symbol
#     {} : The opening and closing curly brackets are used for range definition
#     $ :  The dollar sign is the anchor for the end of the string

emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

def email_filter(email_series, regex_pattern):
     
#     valid_emails = []
    
#     for email in emails:
#         if re.search(regex_pattern, email):
#             valid_emails.append(email)

#     #OR       
    
#     valid_emails = [email for email in email_series if re.search(regex_pattern, email)]
            
    return pd.Series([email for email in email_series if re.search(regex_pattern, email)])
        
print(email_filter(emails, pattern))

0    rameses@egypt.com
1            matt@t.co
2    narendra@modi.com
dtype: object


In [29]:
#26
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weight = pd.Series(np.linspace(1, 10, 10))
print(weight.tolist())
print(fruit.tolist())

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['banana', 'banana', 'carrot', 'carrot', 'carrot', 'carrot', 'carrot', 'banana', 'banana', 'banana']


In [30]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

def euclidean(ser1, ser2):
    sumz = 0
    for n in range(len(ser1)):
        sumz += (ser1[n] - ser2[n])**2
    return sumz**(0.5)

print(euclidean(p, q))

np.sqrt(np.sum([(a-b)**2 for a, b in zip(p,q)]))

18.16590212458495


18.16590212458495

In [31]:
from scipy import signal

ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
maximums = signal.argrelextrema(np.array(ser), np.greater)

print(maximums)

# dd = np.diff(np.sign(np.diff(ser)))
# peak_locs = np.where(dd == -2)[0] + 1
# peak_locs

(array([1, 5, 7]),)


In [32]:
#29
my_str = 'dbc deb abed gade'
ser = pd.Series(list(my_str))
freq = ser.value_counts()
print(freq)
least_freq = freq.dropna().index[-1]
"".join(ser.replace(' ', least_freq))

d    4
b    3
     3
e    3
a    2
g    1
c    1
dtype: int64


'dbccdebcabedcgade'

In [33]:
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000', freq='W-SAT', periods=10))
ser

2000-01-01    2
2000-01-08    1
2000-01-15    6
2000-01-22    1
2000-01-29    7
2000-02-05    2
2000-02-12    2
2000-02-19    3
2000-02-26    4
2000-03-04    4
Freq: W-SAT, dtype: int64

In [34]:
#31
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64


In [35]:
#32
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
print(autocorrelations[1:])
print('Lag having highest correlation: ', np.argmax(np.abs(autocorrelations[1:]))+1)

[-0.54, 0.22, 0.08, -0.05, 0.32, -0.52, 0.65, -0.38, 0.06, -0.1]
Lag having highest correlation:  7


In [36]:
#33
def logic(x):
    if x%50 == 0: True
boston = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', skiprows=lambda x: logic(x))
# boston = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', skiprows=lambda x: True if x%50 == 0 else False)

In [37]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.DataFrame()
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])

In [38]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.concat([chunk.iloc[0] for chunk in df], axis=1)
df2 = df2.transpose()

In [39]:
b = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')
out = []
for i, row in enumerate(b.index):
    print
    if i%50 == 0:
        out.append(row)

print(out)
df2 = pd.DataFrame(out[1:], columns=out[0])
print(df2.head())

[0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500]


TypeError: Index(...) must be called with a collection of some kind, 0 was passed

In [ ]:
#34
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', converters={'medv': lambda x: 'High' if float(x) > 25 else 'Low'})

# import csv
# with open('BostonHousing.csv', 'r') as f:
#     reader = csv.reader(f)
#     out = []
#     for i, row in enumerate(reader):
#         if i > 0:
#             row[13] = 'High' if float(row[13]) > 25 else 'Low'
#         out.append(row)
        
# df2 = pd.DataFrame(out[1:], columns=out[0])
# print(df.head())

df.head()

In [42]:
#35
L = pd.Series(range(15))

def gen_strides(a, stride_len=2, window_len=4):
    
    n_strides = ((a.size - window_len) // stride_len) + 1
    
    return np.array([a[s: (s + window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

print(gen_strides(L))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]


In [43]:
#36
file = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'
cols = ['crim', 'medv']
pd.read_csv(file, usecols=cols)

crim  medv
0    0.00632  24.0
1    0.02731  21.6
2    0.02729  34.7
3    0.03237  33.4
4    0.06905  36.2
..       ...   ...
501  0.06263  22.4
502  0.04527  20.6
503  0.06076  23.9
504  0.10959  22.0
505  0.04741  11.9

[506 rows x 2 columns]

In [62]:
#37
file = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'
df = pd.read_csv(file)
df.info()
df.describe()
df.dtypes
df.values
df.values.tolist()
df.dtypes.value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Manufacturer        89 non-null     object 
 1   Model               92 non-null     object 
 2   Type                90 non-null     object 
 3   Min.Price           86 non-null     float64
 4   Price               91 non-null     float64
 5   Max.Price           88 non-null     float64
 6   MPG.city            84 non-null     float64
 7   MPG.highway         91 non-null     float64
 8   AirBags             87 non-null     object 
 9   DriveTrain          86 non-null     object 
 10  Cylinders           88 non-null     object 
 11  EngineSize          91 non-null     float64
 12  Horsepower          86 non-null     float64
 13  RPM                 90 non-null     float64
 14  Rev.per.mile        87 non-null     float64
 15  Man.trans.avail     88 non-null     object 
 16  Fuel.tank.

float64    18
object      9
dtype: int64

In [67]:
#38
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.head()

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [86]:
manufacturer = df[df.loc[:, 'Price'] == df.loc[:, 'Price'].max()]

df.loc[df.Price == np.max(df.Price), ['Manufacturer', 'Model', 'Type']]

row, col = np.where(df.values == np.max(df.Price))

df.iat[row[0], col[0]]
df.iloc[row[0], col[0]]

df.at[row[0], 'Price']

61.9

In [94]:
#39
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.rename(columns={'Type': 'CarType'}, inplace=True)

df.columns = df.columns.map(lambda x: x.replace('.', '_'))
            
df.head()

Manufacturer    Model  CarType  Min_Price  Price  Max_Price  MPG_city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG_highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn_circle Rear_seat_room  Luggage_room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [ ]:
#40
